/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./site/**/*.html", "./templates/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#fff6f4",
        "background": "#faf9f5",
        "on-secondary-container": "#525151",
        "on-tertiary-container": "#4d6051",
        "on-primary-fixed": "#7e140b",
        "inverse-surface": "#0d0f0d",
        "secondary-container": "#e5e2e1",
        "on-primary-container": "#99281c",
        "surface-container-high": "#e6e9e2",
        "secondary-dim": "#545353",
        "error-dim": "#4e0309",
        "inverse-on-surface": "#9d9d9a",
        "error-container": "#fe8983",
        "tertiary-fixed": "#e4f9e5",
        "tertiary": "#506454",
        "surface-container": "#edeee8",
        "primary-dim": "#9a291d",
        "on-background": "#2f342e",
        "surface": "#faf9f5",
        "on-surface-variant": "#5c605a",
        "primary-fixed": "#ffdad4",
        "secondary": "#605f5f",
        "primary-container": "#ffdad4",
        "surface-container-highest": "#e0e4dc",
        "on-secondary-fixed-variant": "#5c5b5b",
        "on-error-container": "#752121",
        "outline-variant": "#afb3ac",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffc7bf",
        "on-tertiary-fixed": "#3b4e40",
        "surface-variant": "#e0e4dc",
        "surface-tint": "#aa3527",
        "surface-container-low": "#f4f4ef",
        "tertiary-dim": "#455849",
        "surface-bright": "#faf9f5",
        "on-secondary": "#fbf8f8",
        "surface-dim": "#d6dcd2",
        "inverse-primary": "#f86d5a",
        "primary": "#aa3527",
        "on-tertiary-fixed-variant": "#576b5b",
        "on-primary-fixed-variant": "#a63225",
        "on-tertiary": "#e9ffeb",
        "tertiary-fixed-dim": "#d5ebd7",
        "tertiary-container": "#e4f9e5",
        "on-surface": "#2f342e",
        "outline": "#787c75",
        "error": "#9f403d",
        "secondary-fixed-dim": "#d6d4d3",
        "secondary-fixed": "#e5e2e1",
        "on-error": "#fff7f6",
        "on-secondary-fixed": "#403f3f"
      },
      fontFamily: {
        "headline": ["Newsreader"],
        "body": ["Public Sans"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
